ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
#RUN bin/kibana-plugin install https://url/to/search-guard-kibana-plugin-6.6.0-24.1.zip
#RUN  bin/kibana-plugin install https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-kibana-plugin/6.6.0-18.1/search-guard-kibana-plugin-6.6.0-18.1.zip 
#RUN bin/kibana-plugin install x-pack
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
