---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
# Use HTTPS instead of HTTP
elasticsearch.url: "http://elasticsearch:9200"

# Configure the Kibana internal server user
#elasticsearch.username: "kibanaserver"
#elasticsearch.password: "kibanaserver"

# Disable SSL verification because we use self-signed demo certificates
#elasticsearch.ssl.verificationMode: none

# Whitelist the Search Guard Multi Tenancy Header
#elasticsearch.requestHeadersWhitelist: [ "Authorization", "sgtenant" ]

