ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}

#RUN bin/logstash-plugin install x-pack

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
